// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

// Injectors from wire.go:

func initializeApp() (*App, error) {
	config, err := WithCfg()
	if err != nil {
		return nil, err
	}
	logger, err := WithLogger(config)
	if err != nil {
		return nil, err
	}
	engine, err := WithGinEngine(config, logger)
	if err != nil {
		return nil, err
	}
	appApp := &App{
		cfg:       config,
		logger:    logger,
		ginEngine: engine,
	}
	return appApp, nil
}
